version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    auto-merge: true
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    auto-merge: true
