[tool.poetry]
name = "squirrelfocus"
version = "0.1.0"
description = "Developer productivity and reflection toolkit."
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
typer = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
black = "*"
ruff = "*"

[tool.poetry.scripts]
sf = "cli:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
