name: AI Build

on:
  pull_request:
  issues:

jobs:
  automate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          poetry install --no-root
      - name: Run sf ask
        env:
          QUESTION: >-
            ${{ github.event.pull_request.title || github.event.issue.title }}
        run: poetry run sf ask "$QUESTION" || true
