name: CI Summary from Trailers
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  summarize:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install PyYAML
        timeout-minutes: 15
        run: |
          python -m pip install --upgrade pip
          pip install "PyYAML>=6,<7"
      - name: Emit CI Summary
        timeout-minutes: 15
        run: |
          python3 scripts/sqf_emit.py summary > summary.md || true
          if [ -s summary.md ]; then
            cat summary.md >> $GITHUB_STEP_SUMMARY
          else
            echo "No summary available" >> $GITHUB_STEP_SUMMARY
          fi
      - name: Comment CI Summary
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const post = require('./scripts/post_triage_comment.js');
            await post({github, context, core});
