name: CI Summary from Trailers
on: [push, pull_request]
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  summarize:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install PyYAML
        run: |
          python -m pip install --upgrade pip
          pip install "PyYAML>=6,<7"
      - name: Emit CI Summary
        run: |
          python3 scripts/sqf_emit.py summary > summary.md || true
          if [ -s summary.md ]; then
            cat summary.md >> $GITHUB_STEP_SUMMARY
          else
            echo "No summary available" >> $GITHUB_STEP_SUMMARY
          fi
