name: Merge Log
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  append-log:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install PyYAML
        run: |
          python -m pip install --upgrade pip
          pip install "PyYAML>=6,<7"
      - name: Build log line
        run: |
          line="- $(date -u +%F) — $(python3 scripts/sqf_emit.py \
            trailers | tr '\n' '; ')"
          echo "$line" >> MILESTONE_LOG.md
      - name: Commit log
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add MILESTONE_LOG.md
          git commit -m "chore: append milestone log" || echo "No changes"
          git push
