name: Release Publish

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        run: pip install poetry==1.8.3
      - name: Install dependencies
        run: poetry install --no-root --no-interaction
      - name: Build
        run: poetry build
      - name: Publish to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry config pypi-token.pypi "$PYPI_API_TOKEN"
          poetry publish --no-interaction
